### ISSUE TITLE
Can't reset DB (Missing file app/assets/images/chocolate_day_2024.jpg)

### ISSUE THREAD

**Issue by kidsupcode** [Brett-Tanner/db_prototype_v2#1]
Might be waiting for this file from another member of the team, but currently can't log into the system without it.

**Comment by Brett-Tanner** [comment]
I removed the images from git to save space/because having them in there makes it more annoying to upload to AWS. I'll put them all [here](https://drive.google.com/drive/folders/1NyoyFvvad7gDi8ZvRcFLtT6Zz1t7OgJU?usp=sharing) so you can redownload them if needed.

**Comment by kidsupcode** [comment]
Ok

**Comment by Brett-Tanner** [comment]
On second thoughts it is really annoying to have to manually download the images every time, I've returned the test images to git.
